export const TestData = {
  mutators: ["ILY", "TTYL", "BBY"],
  runs: [
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=s7mesGq4_hc",
      type: "Exterminator",
      time: 60,
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
      type: "Slasher",
      time: 60,
    },
    {
      img: "player-Zombonis",
      name: "Dr Zombonis",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
      type: "Slasher",
      time: 60,
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=bp1FIrgrUGo&t=4s",
      type: "Fixer",
      time: 60,
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=rYTNJCAL-XM",
      type: "Gunslinger",
      time: 60,
    },
  ],
};
