export const PlayerData = {
  mutators: ["Rookie", "Looting Is a Crime", "Shaky Hands"],
  runs: [
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=s7mesGq4_hc",
      type: "Exterminator",
      time: 1186,
      rating: "Exceptional",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
      type: "Slasher",
      time: 975,
      rating: "Masterful",
    },
    {
      img: "player-Zombonis",
      name: "Dr Zombonis",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
      type: "Slasher",
      time: 992,
      rating: "Skillful",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=bp1FIrgrUGo&t=4s",
      type: "Fixer",
      time: 791,
      rating: "Outstanding",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=rYTNJCAL-XM",
      type: "Gunslinger",
      time: 1110,
      rating: "Remarkable",
    },
    {
      img: "player-richt",
      name: "Rich T",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=qCC7dUj0FeI",
      type: "Gunslinger",
      time: 784,
      rating: "Flawless",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1Yi4y1i7eG/",
      type: "Slasher",
      time: 963,
      rating: "Dominant",
    },
  ],
};
