export const StatRun = {
  runs: [
    {
      img: "player-aedonis",
      name: "Aedonis",
      map: "Descent",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=YVDekxwGXsA",
      stat: "100% Headshot",
      statInfo: "(957/957)",
      class: "Medic",
      team: "SOLO",
    },
    {
      img: "player-aedonis",
      name: "Aedonis",
      map: "Descent",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=Iv-NSDJ2Pow",
      stat: "100% Headshot",
      statInfo: "(863/863)",
      class: "Gunslinger",
      team: "SOLO",
    },
    {
      img: "players/player-野口 ハヤシ",
      name: "Noguchi",
      map: "French Resistance",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=RPYSq6MYrsY",
      stat: "Team 0 Damage Taken",
      statInfo: "4 Players",
      class: "",
      team: "TEAM",
    },
    {
      img: "player-rasmuspost",
      name: "RasmusPost",
      map: "Phoenix",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=Z2htrW7OxfQ",
      stat: "Full Clear",
      statInfo: "With Bot",
      class: "Gunslinger",
      team: "SOLO",
    },
    {
      img: "player-zombieflanders",
      name: "ZombieFlanders",
      map: "New York",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=fFHbJM1jkio&t=13s",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
    },
    {
      img: "player-zombieflanders",
      name: "ZombieFlanders",
      map: "Marseille",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=j6esDGtHjF0",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
    },
    {
      img: "player-zombieflanders",
      name: "ZombieFlanders",
      map: "Tokyo",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=4NLMsf5bu_E&t=27s",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Episode 1-7",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=liNEw67EwnA",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
    },
    {
      img: "players/player-xD3viLz",
      name: "xD3viLz",
      map: "Episode 1-5",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=pvMvYV7tCQs",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "Gunslinger",
      team: "SOLO",
    },
  ],
};
