export const StatRun = {
  runs: [
    {
      img: "player-aedonis",
      name: "𝔇𝔬𝔫𝔦𝔰𓆩♡𓆪",
      map: "Descent",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=YVDekxwGXsA",
      stat: "100% Headshot",
      statInfo: "(957/957)",
      class: "Medic",
      team: "SOLO",
      ring: "purple",
    },
    {
      img: "player-aedonis",
      name: "𝔇𝔬𝔫𝔦𝔰𓆩♡𓆪",
      map: "Descent",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=Iv-NSDJ2Pow",
      stat: "100% Headshot",
      statInfo: "(863/863)",
      class: "Gunslinger",
      team: "SOLO",
      ring: "purple",
    },
    {
      img: "players/player-野口 ハヤシ",
      name: "Noguchi",
      map: "French Resistance",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=RPYSq6MYrsY",
      stat: "Team 0 Damage Taken",
      statInfo: "4 Players",
      class: "",
      team: "TEAM",
      ring: "yellow",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Episode 1-7",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=liNEw67EwnA",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
      ring: "violet",
    },
    {
      img: "players/player-xD3viLz",
      name: "xD3viLz",
      map: "Episode 1-5",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=pvMvYV7tCQs",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "Gunslinger",
      team: "SOLO",
      ring: "darkblue",
    },
  ],
};
