export const StatRun = {
  runs: [
    {
      img: "player-aedonis",
      name: "Aedonis",
      map: "Descent",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=Iv-NSDJ2Pow",
      stat: "100% Headshot",
      statInfo: "(863/863)",
      class: "Gunslinger",
      team: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Episode 1-7",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=liNEw67EwnA",
      stat: "No Damage",
      statInfo: "No Bot",
      class: "",
      team: "SOLO",
    },
    {
      img: "players/player-xD3viLz",
      name: "xD3viLz",
      map: "Episode 1-5",
      diff: "Extreme",
      src: "https://www.youtube.com/watch?v=pvMvYV7tCQs",
      stat: "Full Clear",
      statInfo: "No Bot",
      class: "Gunslinger",
      team: "SOLO",
    },
  ],
};
