export const Week4 = {
  mutators: ["Looting Is A Crime", "Gun Shortage", "Looter"],
  runs: [
    {
      img: "player-richt",
      name: "Rich T",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=xtoniitNUDs",
      time: 672,
      rating: "TEAM",
    },
    {
      img: "player-zMeba",
      name: "zMeba",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=IF8VOMfQ0E4",
      time: 1255,
      rating: "TEAM",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=XNY41nYSTTM",
      time: 1244,
      rating: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=lh1CeWI02Cc",
      time: 1083,
      rating: "SOLO",
    },
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=Ym7P9ORusWU",
      time: 1132,
      rating: "SOLO",
    },
    {
      img: "player-H3C4T32",
      name: "H3C4T32",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=tuOcgSDJmI4",
      time: 1176,
      rating: "SOLO",
    },
    {
      img: "player-osanai",
      name: "♡osanai♡",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=WU71AnCEPUc",
      time: 887,
      rating: "TEAM",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=xEM9QFRzf2E",
      time: 926,
      rating: "SOLO",
    },
    {
      img: "player-Abang",
      name: "Abang Long",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=H33uJTaasZ4",
      time: 950,
      rating: "SOLO",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1DC4y167Au/",
      time: 690,
      rating: "SOLO",
    },
  ],
};
