export const Week0 = {
  mutators: ["Just a Scratch", "Asthma", "Limited Reach"],
  runs: [
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=Pkw6H02q4hw",
      time: 1142,
      rating: "SOLO",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=W4-XvXaUiZk",
      time: 1072,
      rating: "SOLO",
    },
    {
      img: "player-Zombonis",
      name: "Dr Zombonis",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=zT9b7oyyZrA",
      time: 1779,
      rating: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=kLWr3LLFPIU",
      time: 926,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=J4_ZOfyoMBI",
      time: 1448,
      rating: "SOLO",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Tunnel Vision",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1d5411B7VB/",
      time: 1147,
      rating: "SOLO",
    },
  ],
};
