export const Week6 = {
  mutators: ["Lifebuoy", "Night Time", "1 UP"],
  runs: [
    {
      img: "player-zMeba",
      name: "zMeba",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=KbWRBRufgXk",
      time: 1068,
      rating: "TEAM",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=ZlqhQFBap1k",
      time: 1183,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=pykIJ7lX6Os",
      time: 1219,
      rating: "SOLO",
    },
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=AaGcngQ-3RM",
      time: 1141,
      rating: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=TcMoiDUhUwU",
      time: 924,
      rating: "SOLO",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1Tz421d7zR/",
      time: 918,
      rating: "SOLO",
    },
    {
      img: "player-richt",
      name: "Rich T",
      map: "Tech Support",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=Dec-0nqiAMU",
      time: 923,
      rating: "TEAM",
    },
  ],
};
