export const Week2 = {
  mutators: ["Rookie", "Looting Is a Crime", "Shaky Hands"],
  runs: [
    {
      img: "player-enderlem",
      name: "Enderlem",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=J36yPCGu8Vc&t=132s",
      time: 1017,
      rating: "SOLO",
    },
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=s7mesGq4_hc",
      time: 1186,
      rating: "SOLO",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
      time: 975,
      rating: "SOLO",
    },
    {
      img: "player-Zombonis",
      name: "Dr Zombonis",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
      time: 992,
      rating: "TEAM",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=bp1FIrgrUGo&t=4s",
      time: 791,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=rYTNJCAL-XM",
      time: 1110,
      rating: "SOLO",
    },
    {
      img: "player-richt",
      name: "Rich T",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=qCC7dUj0FeI",
      time: 784,
      rating: "TEAM",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Descent",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1Yi4y1i7eG/",
      time: 963,
      rating: "SOLO",
    },
  ],
};
