export const Week1 = {
  mutators: ["Small Pharma", "CW: Medic", "Die Hard"],
  runs: [
    {
      img: "player-enderlem",
      name: "Enderlem",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=fvS8U4n79yk",
      type: "Gunslinger",
      time: 1036,
      rating: "SOLO",
    },
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=OQVn3h7p8tU",
      type: "Gunslinger",
      time: 1088,
      rating: "SOLO",
    },
    {
      img: "player-Rainiere",
      name: "Rainiere888",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=hZD5fU8xDoU",
      type: "Medic",
      time: 1278,
      rating: "SOLO",
    },
    {
      img: "player-Zombonis",
      name: "Dr Zombonis",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=gEYHoL-X998",
      type: "Dronemaster",
      time: 1026,
      rating: "TEAM",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=36SwcHclH-g",
      type: "Medic",
      time: 1149,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=bDB5OuOWfGE",
      type: "Medic",
      time: 1360,
      rating: "SOLO",
    },
    {
      img: "player-richt",
      name: "Rich T",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=42WUQHs52oE",
      type: "Exterminator",
      time: 665,
      rating: "TEAM",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Brain Surgery",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV17w411g79p/",
      type: "Dronemaster",
      time: 950,
      rating: "SOLO",
    },
  ],
};
