export const Week3 = {
  mutators: ["Mined Corpses", "Light Waves", "Hunger"],
  runs: [
    {
      img: "player-Abang",
      name: "Abang Long",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=VO0i5ARXJX4&t=1s",
      time: 876,
      rating: "SOLO",
    },
    {
      img: "player-enderlem",
      name: "Enderlem",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=MyL3KmhB-U0",
      time: 773,
      rating: "SOLO",
    },
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=8eDyUZcYa-g",
      time: 922,
      rating: "SOLO",
    },
    // {
    //   img: "player-Rainiere",
    //   name: "Rainiere888",
    //   map: "Battle of Nerves",
    //   diff: "Challenge [Hard]",
    //   src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
    //   time: 975,
    //   rating: "SOLO",
    // },
    // {
    //   img: "player-Zombonis",
    //   name: "Dr Zombonis",
    //   map: "Battle of Nerves",
    //   diff: "Challenge [Hard]",
    //   src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
    //   time: 992,
    //   rating: "TEAM",
    // },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=_jlQa6fEAwM&t=2s",
      time: 644,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=P_hr1iNrPR8",
      time: 933,
      rating: "SOLO",
    },
    // {
    //   img: "player-richt",
    //   name: "Rich T",
    //   map: "Battle of Nerves",
    //   diff: "Challenge [Hard]",
    //   src: "https://www.youtube.com/watch?v=qCC7dUj0FeI",
    //   time: 784,
    //   rating: "TEAM",
    // },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV1N5411y7jC/",
      time: 635,
      rating: "SOLO",
    },
    {
      img: "player-Vinhtrn",
      name: "Vinhtrn",
      map: "Battle of Nerves",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=_MU6OnrajeA",
      time: 951,
      rating: "TEAM",
    },
  ],
};
