export const Week5 = {
  mutators: ["Pinned Down", "Weakness", "Slasher CW"],
  runs: [
    {
      img: "player-NieR",
      name: "NieR 777",
      map: "Hell and High Water",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=STZyKAH5-4Q",
      time: 1126,
      rating: "SOLO",
    },
    {
      img: "player-richt",
      name: "Rich T",
      map: "Hell and High Water",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=hsj84N0UMqU",
      time: 806,
      rating: "TEAM",
    },
    {
      img: "player-osanai",
      name: "♡osanai♡",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=9ySu9_ds7wQ",
      time: 929,
      rating: "TEAM",
    },
    {
      img: "player-Abang",
      name: "Abang Long",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=oPbRGFwPdy8",
      time: 893,
      rating: "SOLO",
    },
    {
      img: "player-SiberianPsych0",
      name: "SiberianPsych0",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=fyx3leMkkMU&t=412s",
      time: 690,
      rating: "SOLO",
    },
    {
      img: "player-玉米大战僵尸",
      name: "玉米大战僵尸",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.bilibili.com/video/BV157421N7nX/",
      time: 698,
      rating: "SOLO",
    },
    {
      img: "player-visbell",
      name: "visbell",
      map: "Key to the City",
      diff: "Challenge [Hard]",
      src: "https://www.youtube.com/watch?v=xhKnu6W3r0s",
      time: 1161,
      rating: "SOLO",
    },
  ],
};
