export const HordePlayer = [
  {
    id: 1,
    img: "players/maobai.png",
    name: "貓白",
    mark: "Maobai Pro",
  },
  {
    id: 2,
    img: "players/maobai-team.png",
    name: "前夜",
    mark: "Maobai Pro",
  },
  {
    id: 3,
    img: "players/maobai-team2.png",
    name: "fachen128",
    mark: "Maobai Pro",
  },
  {
    id: 4,
    img: "players/maobai-4.png",
    name: "越",
    mark: "Maobai Pro",
  },
  {
    id: 5,
    img: "players/sleepingdragon.gif",
    name: "睡姿",
    mark: "Maobai Pro",
  },
  {
    id: 6,
    img: "players/littlestar.gif",
    name: "小星星",
    mark: "Maobai Pro",
  },
  {
    id: 7,
    img: "players/player-circle.png",
    name: "圈圈",
    mark: "Maobai Pro",
  },
  {
    id: 8,
    img: "players/maobai-ocean.png",
    name: "七色海洋",
    mark: "Maobai Pro",
  },
  {
    id: 9,
    img: "players/singledog.gif",
    name: "单身狗",
    mark: "Maobai Pro",
  },
  {
    id: 10,
    img: "players/dream.gif",
    name: "蕉鹿梦",
    mark: "Maobai Pro",
  },
  {
    id: 11,
    img: "players/player-wintersky.png",
    name: "Wintersky",
    mark: "Horde Legends",
  },
  {
    id: 12,
    img: "players/player-gogu.jpg",
    name: "gogu7382",
    mark: "Horde Legends",
  },
  {
    id: 13,
    img: "players/player-Fiction.png",
    name: "XxFriction",
    mark: "Horde Legends",
  },
  {
    id: 14,
    img: "players/player-cris.png",
    name: "Crispokringle",
    mark: "Horde Legends",
  },
  {
    id: 15,
    img: "players/player-hirunknown.png",
    name: "HiRUnknown",
    mark: "Horde Legends",
  },
  {
    id: 16,
    img: "players/player-yupitsmeh.png",
    name: "YupItsMeh",
    mark: "Horde Legends",
  },
];
