export const PlayerData = [
  {
    id: "1",
    img: "player-X",
    name: "Caprice Yuri",
    map: "New York 1",
    diff: "Extreme",
    src: "https://www.youtube.com/",
    type: "Hellraiser",
    time: 60,
  },
  {
    id: "2",
    img: "player-NieR",
    name: "NieR 777",
    map: "Descent",
    diff: "Challenge [Hard]",
    src: "https://www.youtube.com/watch?v=s7mesGq4_hc",
    type: "Exterminator",
    time: 1186,
  },
  {
    id: "3",
    img: "player-Rainiere",
    name: "Rainiere888",
    map: "Descent",
    diff: "Challenge [Hard]",
    src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
    type: "Slasher",
    time: 975,
  },
  {
    id: "4",
    img: "player-Zombonis",
    name: "Dr Zombonis",
    map: "Descent",
    diff: "Challenge [Hard]",
    src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
    type: "Slasher",
    time: 992,
  },
  {
    id: "5",
    img: "player-SiberianPsych0",
    name: "SiberianPsych0",
    map: "Descent",
    diff: "Challenge [Hard]",
    src: "https://www.youtube.com/watch?v=bp1FIrgrUGo&t=4s",
    type: "Fixer",
    time: 791,
  },
  {
    id: "6",
    img: "player-visbell",
    name: "visbell",
    map: "Descent",
    diff: "Challenge [Hard]",
    src: "https://www.youtube.com/watch?v=rYTNJCAL-XM",
    type: "Gunslinger",
    time: 1110,
  },
];
