export const PlayerData = [
  {
    img: "player-X",
    name: "Caprice Yuri",
    mark: "Bunko Only",
    category: "Vanguard",
    quote: "Still Downloading",
    power: 10,
    id: "1",
  },
  {
    img: "player-Osanai",
    name: "Osanai",
    mark: "Hello Kitty",
    category: "Vanguard",
    quote: "Cat Shelter",
    id: "2",
  },
  {
    img: "player-aedonis",
    name: "Aedonis",
    mark: "Kimiko Cult",
    category: "Vanguard",
    quote: "Only NY1",
    id: "3",
  },
  {
    img: "player-Tina",
    name: "Zero Two",
    mark: "Kimiko Cult",
    category: "Vanguard",
    quote: "Still AFK",
    id: "4",
  },
  {
    img: "player-Mew",
    name: "Mentality",
    mark: "Kimiko Cult",
    category: "Vanguard",
    quote: "Trap In PVP",
    id: "5",
  },
  {
    img: "player-imperion",
    name: "Imperion",
    mark: "Kimiko Cult",
    category: "Vanguard",
    quote: "Spam Shield",
    id: "6",
  },
];
