export const PlayerData = [
  {
    id: "1",
    img: "player-X",
    name: "Caprice Yuri",
    mark: "Bunko Only",
    map: "New York 1",
    diff: "Extreme",
    src: "https://www.youtube.com/",
  },
  {
    id: "2",
    img: "player-NieR",
    name: "NieR 777",
    map: "Descent",
    diff: "Challenge Mode [Hard]",
    src: "https://www.youtube.com/watch?v=s7mesGq4_hc",
  },
  {
    id: "3",
    img: "player-Rainiere",
    name: "Rainiere888",
    map: "Descent",
    diff: "Challenge Mode [Hard]",
    src: "https://www.youtube.com/watch?v=RToV-UtGn9M",
  },
  {
    id: "4",
    img: "player-Zombonis",
    name: "Dr Zombonis",
    map: "Descent",
    diff: "Challenge Mode [Hard]",
    src: "https://www.youtube.com/watch?v=KdxxOMu8yWI",
  },
  {
    id: "5",
    img: "player-SiberianPsych0",
    name: "SiberianPsych0",
    map: "Descent",
    diff: "Challenge Mode [Hard]",
    src: "https://www.youtube.com/watch?v=bp1FIrgrUGo&t=4s",
  },
  {
    id: "6",
    img: "player-visbell",
    name: "visbell",
    map: "Descent",
    diff: "Challenge Mode [Hard]",
    src: "https://www.youtube.com/watch?v=rYTNJCAL-XM",
  },
];
