export const ExtremePlayer = [
  {
    id: 1,
    img: "players/player-xD3viLz.png",
    name: "xD3viLz",
  },
  {
    id: 2,
    img: "players/player-ABA.png",
    name: "ABA",
    mark: "TW HK MY",
  },
  {
    id: 3,
    img: "/players/player-楊楊.png",
    name: "楊楊",
    mark: "TW HK MY",
  },
  {
    id: 4,
    img: "/players/player-龍蝦.png",
    name: "龍蝦",
    mark: "TW HK MY",
  },
  {
    id: 5,
    img: "players/player-原神高手魚片.png",
    name: "原神高手魚片",
    mark: "TW HK MY",
  },
  {
    id: 6,
    img: "players/player-cathybear.png",
    name: "cathybear",
    mark: "TW HK MY",
  },
  {
    id: 7,
    img: "players/player-KSY.gif",
    name: "⁂𝓚𝓼𝔂𝄪",
    mark: "TW HK MY",
  },
  {
    id: 8,
    img: "players/player-雷包VS新手.png",
    name: "雷包VS新手",
    mark: "TW HK MY",
  },
  {
    id: 9,
    img: "players/player-JK.png",
    name: "JK",
    mark: "TW HK MY",
  },
  {
    id: 10,
    img: "players/player-EricHsiao.png",
    name: "Eric Hsiao",
    mark: "TW HK MY",
  },
  {
    id: 11,
    img: "players/player-銀痕.png",
    name: "銀痕",
    mark: "TW HK MY",
  },
  {
    id: 12,
    img: "/players/player-野口 ハヤシ.png",
    name: "Noguchi",
    mark: "TW HK MY",
  },
  {
    id: 13,
    img: "players/player-Sana.png",
    name: "Sana",
    mark: "TW HK MY",
  },
  {
    id: 14,
    img: "players/player-邦邦.png",
    name: "邦邦",
    mark: "TW HK MY",
  },
];
