export const DevData = [
  {
    id: 1,
    img: "player-X",
    name: "♠Caprice♠",
    mark: "Nobody",
    type: 9,
  },
  {
    id: 2,
    img: "dev-Saber",
    name: "Saber Interactive",
    mark: "Developers / Saber",
    type: 1,
  },
  {
    id: 3,
    img: "dev-Andreia",
    name: "Andreia Mendes",
    mark: "Social Media / Saber",
    type: 1,
  },
  {
    id: 4,
    img: "dev-George",
    name: "George",
    mark: "Community / Saber",
    type: 1,
  },
  {
    id: 5,
    img: "player-aedonis",
    name: "Aedonis 𓆩♡𓆪",
    mark: "Mod / Discord",
    type: 2,
  },
  {
    id: 6,
    img: "player-Tina",
    name: "ACE 𝔗𝔦𝔫𝔞 𓆩♡𓆪",
    mark: "Mod / Discord",
    type: 2,
  },
  {
    id: 7,
    img: "player-Mew",
    name: "ACE 𝔗𝔦𝔫𝔞 𓆩♡𓆪",
    mark: "Mod / Discord",
    type: 2,
  },
  {
    id: 8,
    img: "player-Fiction",
    name: "XxFiction",
    mark: "Horde Lord",
    type: 3,
  },
  {
    id: 9,
    img: "player-wintersky",
    name: "Wintersky",
    mark: "Horde Lord",
    type: 3,
  },
  {
    id: 10,
    img: "player-siberia",
    name: "Cool Guy",
    mark: "Tokyo Drifter",
    type: 4,
  },
];
